name = input("Enter your name: ")
result = len(name)
print(result)
result1 = name.find("u")
print(result1)
result2 = name.rfind("j")
print(result2)
result3 = name.capitalize()
print(result3)
result4 = name.upper()
print(result4)
result5 = name.isdigit()
print(result5)
result6 = name.isalpha()
print(result5)